CryptoSystemDissertation/Controllers/ChatboardController.cs
using CryptoSystemDissertation.Common;
using CryptoSystemDissertation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CryptoSystemDissertation.Controllers
{
    public class ChatboardController : Controller
    {
        // GET: Chatboard
        [CryptoAuthorize]
        public ActionResult Index()
        {
            using (CryptoDbContext db = new CryptoDbContext())
            {
                var crtUser = SessionManager.ReturnSessionObject("User") as UserAccount;
                List<UserAccount> registeredUsers = new List<UserAccount>();
                registeredUsers = db.UserAccount.Where(usr => usr.UserID != crtUser.UserID).ToList();
                return View(registeredUsers);
            }
        }

        public ActionResult ChatOn(int userId)
        {
            using (CryptoDbContext db = new CryptoDbContext())
            {
                var user = db.UserAccount.Where(u => u.UserID == userId).FirstOrDefault();
                ViewBag.User = user;
                return View();
            }
           
        }
    }
}

CryptoSystemDissertation/Views/Chatboard/ChatOn.cshtml
@model CryptoSystemDissertation.Models.UserAccount

@{
    ViewBag.Title = "Chat On";
}

<div class="container">
    <h2> The image will be encrypted and sent to @ViewBag.User.FirstName</h2>
    <div class="row">
        <div class="col-lg-5">
            <div class="image-preview"><img class="preview-initial" src="" /></div>
        </div>
        <div class="col-lg-2">
            
        </div>
        <div class="col-lg-5">
            <div class="image-preview"><img class="preview-encrypted" src="" /></div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-5">
            <input class="browse-img" type="file" onchange="ImageProcessor.showImage(this, @ViewBag.User.UserID);" />
        </div>
        <div class="col-lg-2"></div>
        <div class="col-lg-5">
            <button id="btnSendToReceiver" onclick="RSACrypto.SendEncryptedImage(@ViewBag.User.UserID);" class="btn btn-primary full-width hidden">Send encrypted image to @ViewBag.User.FirstName</button>
        </div>
    </div>
</div>

CryptoSystemDissertation/Views/Chatboard/Index.cshtml
@model IEnumerable<CryptoSystemDissertation.Models.UserAccount>
<div class="container">
    <h2>Chatboard</h2>
        <div class="registered-users-holder col-lg-8">
            @foreach (var user in Model)
            {
                <div class="col-lg-4">
                    <div class="card transition">
                        <h2 class="transition">@user.FirstName @user.LastName</h2>
                        <p>@user.Email</p>
                        <div class="cta-container transition" onclick="location.href='@Url.Action("ChatOn", "Chatboard", new { userId = user.UserID})'"><a href="#" class="cta">Message @user.LastName</a></div>
                        <div class="card_circle transition"></div>
                    </div>
                </div>
            }
        </div>
        <div id="myPicturesHolder" class="myPictures-holder col-lg-4">
          
        </div>
</div>
@section Scripts {
   @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    $(document).ready(function () {

        function updateMyImages() {
            location.reload(true);
        }

        MyOperations.GetPicturesForMe();
        setInterval(updateMyImages, 10000);
    })
</script>
}